# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://calvingcamerareviews.com
title: Calving Camera Reviews
email: jarlath.holleran@gmail.com
description: > # "This site reviews the Calving Cameras Systems available. 
  It gives advice about what to think about when desciding the type of system that
  you want to install. It also describes how to set up and configure a 
  Calving Camera System for DIY people who want to intall the cameras 
  by them selves."

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/JarlathHolleran
  - title: github
    url: https://github.com/jholleran/calvingcamerareviews
  - title: linkedin
    url: https://www.linkedin.com/pub/jarlath-holleran/39/295/784
