# Site settings
title: Calving Camera Systems
email: jarlath.holleran@gmail.com
description: > # 
  Calving Cameras Systems is an information and review site that provides the
  best information on how to install a Calving Camera System for your farm. It
  details how to set up and configure the many different types of Calving Camera
  Systems and offers advise on the best products to buy.

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://calvingcamerasystems.com" # the base hostname & protocol for your site
author: Jarlath Holleran
twitter_username: calvingcameras
#github_username:  jholleran
facebook_username: calvingcamerasystems

# Build settings
markdown: kramdown


# Settings for analytics helper
# Set 'provider' to the analytics provider you want to use.
# Set 'provider' to false to turn analytics off globally.
#        
analytics :
  provider : google 
  google : 
    tracking_id : 'UA-54134529-2'

gems:
  - jekyll-sitemap